version: '3'

services:
  app:
    container_name: is-it-up-app
    image: is-it-up-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # host of service to check
      - CHECK_HOST=<host>

      # port of service to check
      - CHECK_PORT=<port>

      # Available languages - in translations.json
      - LANGUAGE=ENGLISH

      # For maintenance purposes
      # - MODE=MAINTENANCE
    volumes:
      - .:/app:delegated
