version: "3"

services:
  app:
    container_name: is-it-up-app
    image: is-it-up-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    #environment:
      # host of service to check
      #CHECK_HOST: host

      # port of service to check
      #CHECK_PORT: port

      # Available languages - in translations.json
      #LANGUAGE: ENGLISH

      # For maintenance purposes
      # MODE=MAINTENANCE

      # titles for main and table pages
      #TITLE_1: Monitoring
      #TITLE_2: Here is your service
    volumes:
      - is-it-up-app:/app/db

volumes:
  is-it-up-app:
